### ISSUE TITLE
Windows Phone 8.1: pouchdb not working

### ISSUE THREAD

**Issue by Heshyo** [nolanlawson/pouchdb-phonegap-cordova#1]
That sample app on WP8.1 gives:

pouchdb is not working
indexeddb is supported
websql is supported

Also in my own app, that works well on iOS (even on old 3GS with iOS 6.1.3) and Android, on WP8.1I get "No valid adapter found.". At first I was explicitly using WebSQL through {adapter: 'websql'}, so I removed the option. But I was still getting the same error, so I added {adapter: 'idb'}, but I still get that same error.

I haven't looked much into it yet as I don't have the WP8.1 device. You said PouchDB works well on WP8+, was someone able to test it on WP8.1?

**Comment by nolanlawson** [comment]
That's really weird. I don't have a WP phone to test on, though, so it's impossible for me to debug.

Can you check whether it's a Cordova thing or not? I.e. try opening up [any one of the live examples from the guide](http://pouchdb.com/guides/databases.html) using Internet Explorer and see if it's possible.

Also could you post the `userAgent` of the phone while you're in Cordova? Just print out `window.navigator.userAgent`. (The one from within Cordova, not within Internet Explorer.)

**Comment by nolanlawson** [comment]
The fact that it says "websql is supported" is very suspicious. Microsoft never implemented that. Confused.

**Comment by Heshyo** [comment]
Thanks Nolan. I asked the user who owns the WP8.1 phone to try that. The User Agent is: "Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; HTC; Windows Phone 8X by HTC)".

When going to http://bl.ocks.org/nolanlawson/bddac54b92c2d8d39241 the content of the text box stays empty.

Then he thought of checking the options in IE and noticed an option like "Allow websites to store content" (sounds like local storage). After checking it, he get "PouchDB is working", and our own app is working too (without specifying any adapters).

He doesn't know if he's the one who unchecked it in the 1st place or if it was like this by default. He'll reinitialize the phone later to check - UPDATE - after reinitializing his phone, the setting is checked by default, so he probably unchecked it for some reason. That's quite an issue if it impacts Cordova.

So we can says PouchDB is working perfectly fine on WP8.1.

**Comment by nolanlawson** [comment]
Sweet, that's very good to know. Next time WP8 issues come up, I'll ask about that checkbox. :)

**Comment by ajeesh13** [comment]
Hi @nolanlawson,

I am facing the same issue here mentioned.I am using microsoft lumia 535.
I have checked the  "Allow websites to store content" option.

var localDB = new PouchDB("testdb", {
  adapter: 'idb'
});

While posting  I have got this error "Adapter is missing" and some times "No Valid adapter".

Please advice how to fix this

Thanks in advance 
Ajeesh KS

**Comment by Heshyo** [comment]
@ajeesh13 Can you try not specifying any adapter, ie just `new PouchDB("testdb");`.

**Comment by ajeesh13** [comment]
@Heshyo 

Thanks for help.

I have tried with your suggestion.But unfortunatly it didn't work.
I have got the error "No valid adapter found".

Do you have any idea

Thanks & Regards
Ajeesh

**Comment by nolanlawson** [comment]
My guess is that somehow the Lumia's user agent is tricking PouchDB into thinking it's Safari, which would disable IndexedDB. @ajeesh13 can you post your user agent please? (`window.navigator.userAgent`)

**Comment by simran100** [comment]
Hi,I am getting PouchDb adapter undefined Error while running my SAPUI5 project on windows 8.1 phone via visual studio. Can someone please help me out,what adapter should i use to run my project on windows 8.1 phone
