### ISSUE TITLE
SQLite plugin now requires "iosDatabaseLocation" parameter

### ISSUE THREAD

**Issue by oodavid** [nolanlawson/pouchdb-phonegap-cordova#2]
Just testing this and see that the SQLite plugin now needs the iosDatabaseLocation parameter to be set. I'm used this to directly connect to SQLite:

```
window.sqlitePlugin.openDatabase({ name: 'hello-world.db', iosDatabaseLocation: 'default' }, function (db) {
  db.executeSql("select length('tenletters') as stringlength", [], function (res) {
    var stringlength = res.rows.item(0).stringlength;
    console.log('got stringlength: ' + stringlength);
  });
});
```

..But I'm unsure how to add the parameter in PouchDB

PS - it looks as though this parameter was only made mandatory 8 hours ago! This edge bleeds.

**Comment by nolanlawson** [comment]
Thanks for the bug report, but this is an issue on PouchDB rather than this demo app: https://github.com/pouchdb/pouchdb/issues/4979
